swagger: "2.0"
info:
  description: "This is used to show the API information"
  version: "1.0.0"
  title: "Image Processing API"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "zhengxing@seattleu.edu"
host: "localhost:5000"
basePath: "/img"
tags:
- name: "image processing"
  description: "Everything about process image"
schemes:
- "http"
paths:
  /resize:
    post:
      tags:
      - "img"
      summary: "resize image"
      description: "resize an image to the size you want"
      produces:
        - "application/octet_stream"
      parameters:
      - name: "w"
        in: "query"
        description: "the width of the image you want to resize to"
        required: true
        type: "integer"
        format: "int64"
      - name: "h"
        in: "query"
        description: "the height of the image you want to resize to"
        required: true
        type: "integer"
        format: "int64"
      - name: "data"
        in: "body"
        description: "the encoded-image string"
        required: true
        schema:
          type: "string"
      responses:
        200:
          description: "successful operation"
        400:
          description: "missing parameters"
  /rotate:
    post:
      tags:
      - "img"
      summary: "rotate image"
      description: "rotate an image with the angle you set"
      produces:
        - "application/octet_stream"
      parameters:
      - name: "angle"
        in: "query"
        description: "the angle of the image you want to rorate with"
        required: true
        type: "integer"
        format: "int64"
      - name: "data"
        in: "body"
        description: "the encoded-image string"
        required: true
        schema:
          type: "string"
      responses:
        200:
          description: "successful operation"
        400:
          description: "missing parameters"
  /flip:
    post:
      tags:
      - "img"
      summary: "flip image"
      description: "flip an image with the direction you set"
      produces:
        - "application/octet_stream"
      parameters:
      - name: "dir"
        in: "query"
        description: "the direction of the image you want to flip with"
        required: true
        type: "integer"
        format: "int64"
      - name: "data"
        in: "body"
        description: "the encoded-image string"
        required: true
        schema:
          type: "string"
      responses:
        200:
          description: "successful operation"
        400:
          description: "missing parameters"
  /gray:
    post:
      tags:
      - "img"
      summary: "gray image"
      description: "convert an image to grayscale"
      produces:
        - "application/octet_stream"
      parameters:
      - name: "data"
        in: "body"
        description: "the encoded-image string"
        required: true
        schema:
          type: "string"
      responses:
        200:
          description: "successful operation"
        400:
          description: "missing parameters"